spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://34.56.50.46:5432/User-service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


      kafka:
        producer:
        consumer:
          bootstrap-servers: localhost:9092
          group-id: user-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: org.userservice.messaging
  mail:
    host: smtp.gmail.com
    port: 587
    username: assg8218@gmail.com
    password:  icft cdbo yixp wugr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret: verylongrandomstringyouwritehere-and-never-commit-an-obvious-password
    expiration: 3600
